/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.frames;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import utils.Utils;

/**
 *
 * @author kyle
 */
public class MainFrame extends javax.swing.JFrame
{

    /**
     * Creates form MainFrame
     */
    public MainFrame()
    {
        initComponents();
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingUtilities.updateComponentTreeUI(this);
            this.setLocationRelativeTo(null);
            this.pack();
        }
        catch (ClassNotFoundException ex)
        {
            Logger.getLogger(MatchFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            Logger.getLogger(MatchFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            Logger.getLogger(MatchFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (UnsupportedLookAndFeelException ex)
        {
            Logger.getLogger(MatchFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        labelTitle = new javax.swing.JLabel();
        panelScoutingDeploy = new javax.swing.JPanel();
        buttonScoutingNewMatch = new javax.swing.JButton();
        buttonScoutingNewActive = new javax.swing.JButton();
        panelDataDisplayMatch = new javax.swing.JPanel();
        labelDataDisplayMatchLocal = new javax.swing.JLabel();
        labelDataDisplayMatchServer = new javax.swing.JLabel();
        panelDataDisplayActive = new javax.swing.JPanel();
        labelDataDisplayActiveLocal = new javax.swing.JLabel();
        labelDataDisplayActiveServer = new javax.swing.JLabel();
        menuBarTop = new javax.swing.JMenuBar();
        menuServer = new javax.swing.JMenu();
        menuServerSync = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Team 467 2015 Scouting Program");
        setResizable(false);

        labelTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTitle.setText("Team 467 Scouting Software");

        panelScoutingDeploy.setBorder(javax.swing.BorderFactory.createTitledBorder("Scouting"));

        buttonScoutingNewMatch.setText("New Match Scout");
        buttonScoutingNewMatch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonScoutingNewMatchActionPerformed(evt);
            }
        });

        buttonScoutingNewActive.setText("New Active Scout");
        buttonScoutingNewActive.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonScoutingNewActiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelScoutingDeployLayout = new javax.swing.GroupLayout(panelScoutingDeploy);
        panelScoutingDeploy.setLayout(panelScoutingDeployLayout);
        panelScoutingDeployLayout.setHorizontalGroup(
            panelScoutingDeployLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScoutingDeployLayout.createSequentialGroup()
                .addComponent(buttonScoutingNewMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonScoutingNewActive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelScoutingDeployLayout.setVerticalGroup(
            panelScoutingDeployLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScoutingDeployLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(buttonScoutingNewMatch)
                .addComponent(buttonScoutingNewActive))
        );

        panelDataDisplayMatch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Match Scouting Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        labelDataDisplayMatchLocal.setText("Local Scouts: ");

        labelDataDisplayMatchServer.setText("Server Scouts: ");

        javax.swing.GroupLayout panelDataDisplayMatchLayout = new javax.swing.GroupLayout(panelDataDisplayMatch);
        panelDataDisplayMatch.setLayout(panelDataDisplayMatchLayout);
        panelDataDisplayMatchLayout.setHorizontalGroup(
            panelDataDisplayMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataDisplayMatchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDataDisplayMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDataDisplayMatchLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDataDisplayMatchServer, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelDataDisplayMatchLayout.setVerticalGroup(
            panelDataDisplayMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataDisplayMatchLayout.createSequentialGroup()
                .addComponent(labelDataDisplayMatchLocal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDataDisplayMatchServer)
                .addGap(0, 117, Short.MAX_VALUE))
        );

        panelDataDisplayActive.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Active Scouting Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        labelDataDisplayActiveLocal.setText("Local Scouts: ");

        labelDataDisplayActiveServer.setText("Server Scouts: ");

        javax.swing.GroupLayout panelDataDisplayActiveLayout = new javax.swing.GroupLayout(panelDataDisplayActive);
        panelDataDisplayActive.setLayout(panelDataDisplayActiveLayout);
        panelDataDisplayActiveLayout.setHorizontalGroup(
            panelDataDisplayActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataDisplayActiveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDataDisplayActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDataDisplayActiveLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDataDisplayActiveServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelDataDisplayActiveLayout.setVerticalGroup(
            panelDataDisplayActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataDisplayActiveLayout.createSequentialGroup()
                .addComponent(labelDataDisplayActiveLocal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDataDisplayActiveServer)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuServer.setText("Server");

        menuServerSync.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuServerSync.setText("Sync Files");
        menuServerSync.setBorder(null);
        menuServerSync.setBorderPainted(true);
        menuServerSync.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                menuServerSyncActionPerformed(evt);
            }
        });
        menuServer.add(menuServerSync);

        menuBarTop.add(menuServer);

        setJMenuBar(menuBarTop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelScoutingDeploy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelDataDisplayMatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelDataDisplayActive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelScoutingDeploy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDataDisplayMatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDataDisplayActive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonScoutingNewMatchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonScoutingNewMatchActionPerformed
    {//GEN-HEADEREND:event_buttonScoutingNewMatchActionPerformed
        MatchFrame match = new MatchFrame();
    }//GEN-LAST:event_buttonScoutingNewMatchActionPerformed

    private void menuServerSyncActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuServerSyncActionPerformed
    {//GEN-HEADEREND:event_menuServerSyncActionPerformed
        System.out.println("sync...");
        String ip = Utils.showInputBoxAndGetResponse("Enter Server IP", "Server IP");
        System.out.println(ip);
    }//GEN-LAST:event_menuServerSyncActionPerformed

    private void buttonScoutingNewActiveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonScoutingNewActiveActionPerformed
    {//GEN-HEADEREND:event_buttonScoutingNewActiveActionPerformed
        ActiveFrame activeFrame = new ActiveFrame();
        activeFrame.setVisible(true);
    }//GEN-LAST:event_buttonScoutingNewActiveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonScoutingNewActive;
    private javax.swing.JButton buttonScoutingNewMatch;
    private javax.swing.JLabel labelDataDisplayActiveLocal;
    private javax.swing.JLabel labelDataDisplayActiveServer;
    private javax.swing.JLabel labelDataDisplayMatchLocal;
    private javax.swing.JLabel labelDataDisplayMatchServer;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JMenuBar menuBarTop;
    private javax.swing.JMenu menuServer;
    private javax.swing.JMenuItem menuServerSync;
    private javax.swing.JPanel panelDataDisplayActive;
    private javax.swing.JPanel panelDataDisplayMatch;
    private javax.swing.JPanel panelScoutingDeploy;
    // End of variables declaration//GEN-END:variables
}
