/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.frames;

import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import main.Main;
import client.objects.matchdata.CoOpType;
import client.objects.matchdata.HumanPlayerType;
import client.objects.matchdata.MatchData;
import client.objects.matchdata.RobotActivityType;
import client.objects.stacks.StackBase;
import client.objects.stacks.StackContainer;
import client.objects.stacks.StackTote;
import utils.Utils;

/**
 *
 * @author kyle
 */
public class MatchFrame extends javax.swing.JFrame implements ResetableFrame
{

    private static final int SCROLL_SPEED = 16;

    /**
     * Creates new form MatchFrame
     */
    public MatchFrame()
    {
        initComponents();
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingUtilities.updateComponentTreeUI(this);
            this.setLocationRelativeTo(null);
            this.pack();
        }
        catch (ClassNotFoundException ex)
        {
            Logger.getLogger(MatchFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            Logger.getLogger(MatchFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            Logger.getLogger(MatchFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (UnsupportedLookAndFeelException ex)
        {
            Logger.getLogger(MatchFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(true);
    }

    /**
     * Resets the frame to its default values
     */
    @Override
    public void resetFrame()
    {
        fieldMatchNum.setText("");
        fieldScouter.setText("");
        fieldTeamNum.setText("");
        buttonGroupCoop.clearSelection();
        buttonGroupHumanPlayer.clearSelection();
        buttonGroupRobotActive.clearSelection();
        fieldMatchScore.setText("");
        textAreaRobotActivityComments.setText("");
        spinnerNumContainers.setValue(0);
        spinnerNumTotes.setValue(0);
        checkBoxInAutoZone.setSelected(false);
        checkBoxTotesStacked.setEnabled(false);
        checkBoxTotesStacked.setSelected(false);
        checkBoxHPThrewNoodles.setSelected(false);
        radioHPExcellent.setEnabled(false);
        radioHPMediocre.setEnabled(false);
        radioHPPoor.setEnabled(false);
        listContainerStack.setModel(new DefaultListModel<StackBase>());
        listToteStack.setModel(new DefaultListModel<StackBase>());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroupRobotActive = new javax.swing.ButtonGroup();
        buttonGroupCoop = new javax.swing.ButtonGroup();
        buttonGroupHumanPlayer = new javax.swing.ButtonGroup();
        mainPanelScroll = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        buttonSave = new javax.swing.JButton();
        panelTeamInfo = new javax.swing.JPanel();
        labelTeamNum = new javax.swing.JLabel();
        fieldTeamNum = new javax.swing.JTextField();
        labelMatchNum = new javax.swing.JLabel();
        fieldMatchNum = new javax.swing.JTextField();
        labelScouter = new javax.swing.JLabel();
        fieldScouter = new javax.swing.JTextField();
        panelRobotActivity = new javax.swing.JPanel();
        panelRobotActivityRadio = new javax.swing.JPanel();
        radioActiveYes = new javax.swing.JRadioButton();
        radioActiveNo = new javax.swing.JRadioButton();
        radioActivePartial = new javax.swing.JRadioButton();
        panelRobotActivityComments = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaRobotActivityComments = new javax.swing.JTextArea();
        panelScoring = new javax.swing.JPanel();
        panelAutonomous = new javax.swing.JPanel();
        panelAutoScoredTotes = new javax.swing.JPanel();
        labelNumTotes = new javax.swing.JLabel();
        spinnerNumTotes = new javax.swing.JSpinner();
        checkBoxTotesStacked = new javax.swing.JCheckBox();
        panelAutoScoredContainer = new javax.swing.JPanel();
        labelNumContainers = new javax.swing.JLabel();
        spinnerNumContainers = new javax.swing.JSpinner();
        panelAutoScoredRobot = new javax.swing.JPanel();
        checkBoxInAutoZone = new javax.swing.JCheckBox();
        panelTeleop = new javax.swing.JPanel();
        panelTeleopToteStacks = new javax.swing.JPanel();
        buttonAddToteStack = new javax.swing.JButton();
        buttonRemoveToteStack = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listToteStack = new javax.swing.JList<StackBase>();
        panelTeleopContainerStacks = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listContainerStack = new javax.swing.JList<StackBase>();
        buttonAddContainerStack = new javax.swing.JButton();
        buttonRemoveContainerStack = new javax.swing.JButton();
        panelCoop = new javax.swing.JPanel();
        radioCoopNone = new javax.swing.JRadioButton();
        radioCoopUnstacked = new javax.swing.JRadioButton();
        radioCoopStacked = new javax.swing.JRadioButton();
        panelHumanPlayer = new javax.swing.JPanel();
        radioHPPoor = new javax.swing.JRadioButton();
        radioHPMediocre = new javax.swing.JRadioButton();
        radioHPExcellent = new javax.swing.JRadioButton();
        checkBoxHPThrewNoodles = new javax.swing.JCheckBox();
        panelOutcome = new javax.swing.JPanel();
        labelMatchScore = new javax.swing.JLabel();
        fieldMatchScore = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Match Recorder");
        setResizable(false);

        mainPanelScroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        labelTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTitle.setText("Match Recorder");

        buttonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/SaveIconMedium.png"))); // NOI18N
        buttonSave.setMargin(new java.awt.Insets(2, 2, 2, 2));
        buttonSave.setMaximumSize(new java.awt.Dimension(55, 55));
        buttonSave.setMinimumSize(new java.awt.Dimension(55, 55));
        buttonSave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonSaveActionPerformed(evt);
            }
        });

        panelTeamInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Team Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        labelTeamNum.setText("Team #:");

        fieldTeamNum.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                fieldTeamNumKeyReleased(evt);
            }
        });

        labelMatchNum.setText("Match #:");

        fieldMatchNum.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                fieldMatchNumKeyReleased(evt);
            }
        });

        labelScouter.setText("Scouter:");

        javax.swing.GroupLayout panelTeamInfoLayout = new javax.swing.GroupLayout(panelTeamInfo);
        panelTeamInfo.setLayout(panelTeamInfoLayout);
        panelTeamInfoLayout.setHorizontalGroup(
            panelTeamInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTeamInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTeamNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldTeamNum, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMatchNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldMatchNum, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelScouter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldScouter, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTeamInfoLayout.setVerticalGroup(
            panelTeamInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTeamInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelScouter)
                .addComponent(fieldScouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTeamInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(fieldTeamNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(labelTeamNum)
                .addComponent(labelMatchNum)
                .addComponent(fieldMatchNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelRobotActivity.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Robot Activity", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        panelRobotActivityRadio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Active?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        buttonGroupRobotActive.add(radioActiveYes);
        radioActiveYes.setText("Yes");

        buttonGroupRobotActive.add(radioActiveNo);
        radioActiveNo.setText("No");

        buttonGroupRobotActive.add(radioActivePartial);
        radioActivePartial.setText("Partially");

        javax.swing.GroupLayout panelRobotActivityRadioLayout = new javax.swing.GroupLayout(panelRobotActivityRadio);
        panelRobotActivityRadio.setLayout(panelRobotActivityRadioLayout);
        panelRobotActivityRadioLayout.setHorizontalGroup(
            panelRobotActivityRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRobotActivityRadioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRobotActivityRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioActiveYes)
                    .addComponent(radioActiveNo)
                    .addComponent(radioActivePartial))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        panelRobotActivityRadioLayout.setVerticalGroup(
            panelRobotActivityRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRobotActivityRadioLayout.createSequentialGroup()
                .addComponent(radioActiveYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioActiveNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioActivePartial))
        );

        panelRobotActivityComments.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Comments (Optional)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        textAreaRobotActivityComments.setColumns(20);
        textAreaRobotActivityComments.setRows(1);
        jScrollPane1.setViewportView(textAreaRobotActivityComments);

        javax.swing.GroupLayout panelRobotActivityCommentsLayout = new javax.swing.GroupLayout(panelRobotActivityComments);
        panelRobotActivityComments.setLayout(panelRobotActivityCommentsLayout);
        panelRobotActivityCommentsLayout.setHorizontalGroup(
            panelRobotActivityCommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        panelRobotActivityCommentsLayout.setVerticalGroup(
            panelRobotActivityCommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout panelRobotActivityLayout = new javax.swing.GroupLayout(panelRobotActivity);
        panelRobotActivity.setLayout(panelRobotActivityLayout);
        panelRobotActivityLayout.setHorizontalGroup(
            panelRobotActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRobotActivityLayout.createSequentialGroup()
                .addComponent(panelRobotActivityRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRobotActivityComments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRobotActivityLayout.setVerticalGroup(
            panelRobotActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRobotActivityRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelRobotActivityComments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelScoring.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Scoring", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        panelAutonomous.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Autonomous", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        panelAutoScoredTotes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Scored Totes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        labelNumTotes.setText("Scored Totes:");

        spinnerNumTotes.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                spinnerNumTotesStateChanged(evt);
            }
        });
        spinnerNumTotes.addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                spinnerNumTotesPropertyChange(evt);
            }
        });

        checkBoxTotesStacked.setText("Totes Stacked?");
        checkBoxTotesStacked.setEnabled(false);

        javax.swing.GroupLayout panelAutoScoredTotesLayout = new javax.swing.GroupLayout(panelAutoScoredTotes);
        panelAutoScoredTotes.setLayout(panelAutoScoredTotesLayout);
        panelAutoScoredTotesLayout.setHorizontalGroup(
            panelAutoScoredTotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAutoScoredTotesLayout.createSequentialGroup()
                .addGroup(panelAutoScoredTotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAutoScoredTotesLayout.createSequentialGroup()
                        .addComponent(labelNumTotes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerNumTotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkBoxTotesStacked))
                .addGap(0, 78, Short.MAX_VALUE))
        );
        panelAutoScoredTotesLayout.setVerticalGroup(
            panelAutoScoredTotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAutoScoredTotesLayout.createSequentialGroup()
                .addGroup(panelAutoScoredTotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumTotes)
                    .addComponent(spinnerNumTotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxTotesStacked)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelAutoScoredContainer.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Scored Containers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        labelNumContainers.setText("Scored Containers:");

        spinnerNumContainers.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                spinnerNumContainersStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelAutoScoredContainerLayout = new javax.swing.GroupLayout(panelAutoScoredContainer);
        panelAutoScoredContainer.setLayout(panelAutoScoredContainerLayout);
        panelAutoScoredContainerLayout.setHorizontalGroup(
            panelAutoScoredContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAutoScoredContainerLayout.createSequentialGroup()
                .addComponent(labelNumContainers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerNumContainers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 53, Short.MAX_VALUE))
        );
        panelAutoScoredContainerLayout.setVerticalGroup(
            panelAutoScoredContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAutoScoredContainerLayout.createSequentialGroup()
                .addGroup(panelAutoScoredContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumContainers)
                    .addComponent(spinnerNumContainers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelAutoScoredRobot.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Scored Robot", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        checkBoxInAutoZone.setText("In Auto Zone?");

        javax.swing.GroupLayout panelAutoScoredRobotLayout = new javax.swing.GroupLayout(panelAutoScoredRobot);
        panelAutoScoredRobot.setLayout(panelAutoScoredRobotLayout);
        panelAutoScoredRobotLayout.setHorizontalGroup(
            panelAutoScoredRobotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAutoScoredRobotLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkBoxInAutoZone)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAutoScoredRobotLayout.setVerticalGroup(
            panelAutoScoredRobotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAutoScoredRobotLayout.createSequentialGroup()
                .addComponent(checkBoxInAutoZone)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelAutonomousLayout = new javax.swing.GroupLayout(panelAutonomous);
        panelAutonomous.setLayout(panelAutonomousLayout);
        panelAutonomousLayout.setHorizontalGroup(
            panelAutonomousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAutonomousLayout.createSequentialGroup()
                .addComponent(panelAutoScoredTotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAutoScoredContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAutoScoredRobot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAutonomousLayout.setVerticalGroup(
            panelAutonomousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAutoScoredTotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelAutoScoredContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelAutoScoredRobot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelTeleop.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Teleoperated", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        panelTeleopToteStacks.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tote Stacks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        buttonAddToteStack.setText("+");
        buttonAddToteStack.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                buttonAddToteStackMouseClicked(evt);
            }
        });
        buttonAddToteStack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonAddToteStackActionPerformed(evt);
            }
        });

        buttonRemoveToteStack.setText("-");
        buttonRemoveToteStack.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                buttonRemoveToteStackMouseClicked(evt);
            }
        });
        buttonRemoveToteStack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonRemoveToteStackActionPerformed(evt);
            }
        });

        listToteStack.setDoubleBuffered(true);
        jScrollPane3.setViewportView(listToteStack);

        javax.swing.GroupLayout panelTeleopToteStacksLayout = new javax.swing.GroupLayout(panelTeleopToteStacks);
        panelTeleopToteStacks.setLayout(panelTeleopToteStacksLayout);
        panelTeleopToteStacksLayout.setHorizontalGroup(
            panelTeleopToteStacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTeleopToteStacksLayout.createSequentialGroup()
                .addComponent(buttonAddToteStack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRemoveToteStack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );
        panelTeleopToteStacksLayout.setVerticalGroup(
            panelTeleopToteStacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTeleopToteStacksLayout.createSequentialGroup()
                .addGroup(panelTeleopToteStacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddToteStack)
                    .addComponent(buttonRemoveToteStack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
        );

        panelTeleopContainerStacks.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Container Stacks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jScrollPane2.setViewportView(listContainerStack);

        buttonAddContainerStack.setText("+");
        buttonAddContainerStack.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                buttonAddContainerStackMouseClicked(evt);
            }
        });
        buttonAddContainerStack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonAddContainerStackActionPerformed(evt);
            }
        });

        buttonRemoveContainerStack.setText("-");
        buttonRemoveContainerStack.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                buttonRemoveContainerStackMouseClicked(evt);
            }
        });
        buttonRemoveContainerStack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonRemoveContainerStackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTeleopContainerStacksLayout = new javax.swing.GroupLayout(panelTeleopContainerStacks);
        panelTeleopContainerStacks.setLayout(panelTeleopContainerStacksLayout);
        panelTeleopContainerStacksLayout.setHorizontalGroup(
            panelTeleopContainerStacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
            .addGroup(panelTeleopContainerStacksLayout.createSequentialGroup()
                .addComponent(buttonAddContainerStack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRemoveContainerStack)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelTeleopContainerStacksLayout.setVerticalGroup(
            panelTeleopContainerStacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTeleopContainerStacksLayout.createSequentialGroup()
                .addGroup(panelTeleopContainerStacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddContainerStack)
                    .addComponent(buttonRemoveContainerStack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTeleopLayout = new javax.swing.GroupLayout(panelTeleop);
        panelTeleop.setLayout(panelTeleopLayout);
        panelTeleopLayout.setHorizontalGroup(
            panelTeleopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTeleopLayout.createSequentialGroup()
                .addComponent(panelTeleopToteStacks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTeleopContainerStacks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTeleopLayout.setVerticalGroup(
            panelTeleopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTeleopToteStacks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTeleopContainerStacks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelScoringLayout = new javax.swing.GroupLayout(panelScoring);
        panelScoring.setLayout(panelScoringLayout);
        panelScoringLayout.setHorizontalGroup(
            panelScoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAutonomous, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTeleop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelScoringLayout.setVerticalGroup(
            panelScoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScoringLayout.createSequentialGroup()
                .addComponent(panelAutonomous, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTeleop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelCoop.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Coop", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        buttonGroupCoop.add(radioCoopNone);
        radioCoopNone.setText("None");

        buttonGroupCoop.add(radioCoopUnstacked);
        radioCoopUnstacked.setText("Unstacked");

        buttonGroupCoop.add(radioCoopStacked);
        radioCoopStacked.setText("Stacked");

        javax.swing.GroupLayout panelCoopLayout = new javax.swing.GroupLayout(panelCoop);
        panelCoop.setLayout(panelCoopLayout);
        panelCoopLayout.setHorizontalGroup(
            panelCoopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCoopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioCoopNone)
                    .addComponent(radioCoopUnstacked)
                    .addComponent(radioCoopStacked))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        panelCoopLayout.setVerticalGroup(
            panelCoopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoopLayout.createSequentialGroup()
                .addComponent(radioCoopNone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioCoopUnstacked)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioCoopStacked))
        );

        panelHumanPlayer.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Human Player Noodle Throwing", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        buttonGroupHumanPlayer.add(radioHPPoor);
        radioHPPoor.setSelected(true);
        radioHPPoor.setText("Attempted (0 scored noodles)");
        radioHPPoor.setEnabled(false);

        buttonGroupHumanPlayer.add(radioHPMediocre);
        radioHPMediocre.setText("Mediocre (1 to 2 scored noodles)");
        radioHPMediocre.setToolTipText("");
        radioHPMediocre.setEnabled(false);

        buttonGroupHumanPlayer.add(radioHPExcellent);
        radioHPExcellent.setText("Excellent (3+ scored noodles)");
        radioHPExcellent.setActionCommand("Excellent");
        radioHPExcellent.setEnabled(false);

        checkBoxHPThrewNoodles.setText("HP Threw Noodles");
        checkBoxHPThrewNoodles.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                checkBoxHPThrewNoodlesStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelHumanPlayerLayout = new javax.swing.GroupLayout(panelHumanPlayer);
        panelHumanPlayer.setLayout(panelHumanPlayerLayout);
        panelHumanPlayerLayout.setHorizontalGroup(
            panelHumanPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHumanPlayerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkBoxHPThrewNoodles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHumanPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioHPPoor)
                    .addComponent(radioHPMediocre)
                    .addComponent(radioHPExcellent))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHumanPlayerLayout.setVerticalGroup(
            panelHumanPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHumanPlayerLayout.createSequentialGroup()
                .addComponent(radioHPPoor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHumanPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioHPMediocre)
                    .addComponent(checkBoxHPThrewNoodles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioHPExcellent))
        );

        panelOutcome.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Outcome", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        labelMatchScore.setText("Match Total Score:");

        fieldMatchScore.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fieldMatchScoreActionPerformed(evt);
            }
        });
        fieldMatchScore.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                fieldMatchScoreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                fieldMatchScoreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                fieldMatchScoreKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelOutcomeLayout = new javax.swing.GroupLayout(panelOutcome);
        panelOutcome.setLayout(panelOutcomeLayout);
        panelOutcomeLayout.setHorizontalGroup(
            panelOutcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOutcomeLayout.createSequentialGroup()
                .addComponent(labelMatchScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldMatchScore, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelOutcomeLayout.setVerticalGroup(
            panelOutcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOutcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelMatchScore)
                .addComponent(fieldMatchScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(labelTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelTeamInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRobotActivity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelScoring, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(panelCoop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelHumanPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(panelOutcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitle)
                    .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRobotActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelScoring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCoop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelHumanPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOutcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        mainPanelScroll.setViewportView(mainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanelScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanelScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        mainPanelScroll.getVerticalScrollBar().setUnitIncrement(SCROLL_SPEED);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddToteStackMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buttonAddToteStackMouseClicked
    {//GEN-HEADEREND:event_buttonAddToteStackMouseClicked
        
    }//GEN-LAST:event_buttonAddToteStackMouseClicked

    private void buttonAddContainerStackMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buttonAddContainerStackMouseClicked
    {//GEN-HEADEREND:event_buttonAddContainerStackMouseClicked

    }//GEN-LAST:event_buttonAddContainerStackMouseClicked

    private void buttonRemoveContainerStackMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buttonRemoveContainerStackMouseClicked
    {//GEN-HEADEREND:event_buttonRemoveContainerStackMouseClicked
        
    }//GEN-LAST:event_buttonRemoveContainerStackMouseClicked

    private void spinnerNumTotesPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_spinnerNumTotesPropertyChange
    {//GEN-HEADEREND:event_spinnerNumTotesPropertyChange

    }//GEN-LAST:event_spinnerNumTotesPropertyChange

    private void spinnerNumTotesStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_spinnerNumTotesStateChanged
    {//GEN-HEADEREND:event_spinnerNumTotesStateChanged
        int value = (Integer) spinnerNumTotes.getValue();
        int newValue = value;

        //clamp value
        if (value < 0)
        {
            newValue = 0;
        }
        else if (value > 3)
        {
            newValue = 3;
        }
        //set clamped value
        spinnerNumTotes.setValue(newValue);

        //allow for enabling/disabling of stack check
        checkBoxTotesStacked.setEnabled((newValue > 1));
        //removes checkmark if disabled
        checkBoxTotesStacked.setSelected((newValue > 1) ? checkBoxTotesStacked.isSelected() : false);

    }//GEN-LAST:event_spinnerNumTotesStateChanged

    private void spinnerNumContainersStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_spinnerNumContainersStateChanged
    {//GEN-HEADEREND:event_spinnerNumContainersStateChanged
        int value = (Integer) spinnerNumContainers.getValue();
        int newValue = value;

        //clamp value
        if (value < 0)
        {
            newValue = 0;
        }
        else if (value > 3)
        {
            newValue = 3;
        }
        //set clamped value
        spinnerNumContainers.setValue(newValue);
    }//GEN-LAST:event_spinnerNumContainersStateChanged

    private void checkBoxHPThrewNoodlesStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_checkBoxHPThrewNoodlesStateChanged
    {//GEN-HEADEREND:event_checkBoxHPThrewNoodlesStateChanged
        boolean threw = checkBoxHPThrewNoodles.isSelected();
        radioHPPoor.setEnabled(threw);
        radioHPMediocre.setEnabled(threw);
        radioHPExcellent.setEnabled(threw);
        if (!threw)
        {
            buttonGroupHumanPlayer.clearSelection();
        }
    }//GEN-LAST:event_checkBoxHPThrewNoodlesStateChanged

    private void fieldMatchScoreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fieldMatchScoreActionPerformed
    {//GEN-HEADEREND:event_fieldMatchScoreActionPerformed

    }//GEN-LAST:event_fieldMatchScoreActionPerformed

    private void fieldMatchScoreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_fieldMatchScoreKeyTyped
    {//GEN-HEADEREND:event_fieldMatchScoreKeyTyped

    }//GEN-LAST:event_fieldMatchScoreKeyTyped

    private void fieldMatchScoreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_fieldMatchScoreKeyPressed
    {//GEN-HEADEREND:event_fieldMatchScoreKeyPressed

    }//GEN-LAST:event_fieldMatchScoreKeyPressed

    private void fieldMatchScoreKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_fieldMatchScoreKeyReleased
    {//GEN-HEADEREND:event_fieldMatchScoreKeyReleased
        //remove all non-numeric charecters
        fieldMatchScore.setText(utils.Utils.removeNonNumericChars(fieldMatchScore.getText()));
    }//GEN-LAST:event_fieldMatchScoreKeyReleased

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonSaveActionPerformed
    {//GEN-HEADEREND:event_buttonSaveActionPerformed

        if (assessCompletion(true))
        {
            MatchData matchData = scrapeData();
            Main.matchManager.saveUserDataAsFile(matchData);
            //requests user input to reset the frame
            if(Utils.showOKCancelAndGetResponse("Reset frame?", "Reset the match frame?"))
            {
                this.resetFrame();
            }
        }
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void fieldTeamNumKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_fieldTeamNumKeyReleased
    {//GEN-HEADEREND:event_fieldTeamNumKeyReleased
        fieldTeamNum.setText(utils.Utils.removeNonNumericChars(fieldTeamNum.getText()));
    }//GEN-LAST:event_fieldTeamNumKeyReleased

    private void fieldMatchNumKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_fieldMatchNumKeyReleased
    {//GEN-HEADEREND:event_fieldMatchNumKeyReleased
        fieldMatchNum.setText(utils.Utils.removeNonNumericChars(fieldMatchNum.getText()));
    }//GEN-LAST:event_fieldMatchNumKeyReleased

    private void buttonAddToteStackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonAddToteStackActionPerformed
    {//GEN-HEADEREND:event_buttonAddToteStackActionPerformed
        ToteStackDialogue dialogue = new ToteStackDialogue(this);
        dialogue.setVisible(true);
    }//GEN-LAST:event_buttonAddToteStackActionPerformed

    private void buttonAddContainerStackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonAddContainerStackActionPerformed
    {//GEN-HEADEREND:event_buttonAddContainerStackActionPerformed
        ContainerStackDialogue dialogue = new ContainerStackDialogue(this);
        dialogue.setVisible(true);
    }//GEN-LAST:event_buttonAddContainerStackActionPerformed

    private void buttonRemoveContainerStackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonRemoveContainerStackActionPerformed
    {//GEN-HEADEREND:event_buttonRemoveContainerStackActionPerformed
        removeSelectedFromList(listContainerStack);
    }//GEN-LAST:event_buttonRemoveContainerStackActionPerformed

    private void buttonRemoveToteStackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonRemoveToteStackActionPerformed
    {//GEN-HEADEREND:event_buttonRemoveToteStackActionPerformed
        removeSelectedFromList(listToteStack);
    }//GEN-LAST:event_buttonRemoveToteStackActionPerformed

    private void buttonRemoveToteStackMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buttonRemoveToteStackMouseClicked
    {//GEN-HEADEREND:event_buttonRemoveToteStackMouseClicked

    }//GEN-LAST:event_buttonRemoveToteStackMouseClicked

    /**
     * Pulls all data from the form and sticks it in a match data object.
     *
     * @return
     */
    private MatchData scrapeData()
    {
        //GET HP data            
        HumanPlayerType hpType = HumanPlayerType.NO_THROW;
        if (checkBoxHPThrewNoodles.isSelected())
        {
            try
            {
                hpType = HumanPlayerType.valueOf(getSelectedButtonActionCommandOrDefault(buttonGroupHumanPlayer, HumanPlayerType.NO_THROW.toString()));
            }
            catch (Exception ex)
            {
                hpType = HumanPlayerType.NO_THROW;
            }
        }

        //GET COOP data   
        CoOpType coopType;
        try
        {
            coopType = CoOpType.valueOf(getSelectedButtonActionCommandOrDefault(buttonGroupCoop, CoOpType.NONE.toString()));
        }
        catch (Exception ex)
        {
            coopType = CoOpType.NONE;
        }

        //GET robotActive data 
        RobotActivityType rbtActType;
        try
        {
            rbtActType = RobotActivityType.valueOf(getSelectedButtonActionCommandOrDefault(buttonGroupRobotActive, RobotActivityType.INACTIVE.toString()));
        }
        catch (Exception ex)
        {
            rbtActType = RobotActivityType.INACTIVE;
        }
        String rbtActComment = textAreaRobotActivityComments.getText().trim();

        //GET StackTotes            
        ListModel<StackBase> listModel = listToteStack.getModel();
        StackTote[] stackTotes = new StackTote[listModel.getSize()];
        for (int i = 0; i < listModel.getSize(); i++)
        {
            stackTotes[i] = (StackTote) listModel.getElementAt(i);
        }

        //GET StackContainer
        listModel = listContainerStack.getModel();
        StackContainer[] stackContainers = new StackContainer[listModel.getSize()];
        for (int i = 0; i < listModel.getSize(); i++)
        {
            stackContainers[i] = (StackContainer) listModel.getElementAt(i);
        }

        //GET Scouter data
        int matchNum = Integer.valueOf(fieldMatchNum.getText());
        int teamNum = Integer.valueOf(fieldTeamNum.getText());
        String scouter = fieldScouter.getText();

        //GET Auto data
        int autoNumContainers = (int) spinnerNumContainers.getValue();
        int autoNumTotes = (int) spinnerNumTotes.getValue();
        boolean autoTotesStacked = checkBoxTotesStacked.isSelected();
        boolean autoInAutoZone = checkBoxInAutoZone.isSelected();

        //GET final match data
        int finalScore = Integer.parseInt(fieldMatchScore.getText());

        return new MatchData(matchNum, teamNum, scouter, autoNumTotes, autoNumContainers, autoTotesStacked, autoInAutoZone, stackTotes, stackContainers, rbtActType, rbtActComment, coopType, hpType, finalScore);

    }

    /**
     * Checks to see if all fields are completed
     *
     * @return passed - if passed completion inspection
     */
    private boolean assessCompletion(boolean reportErrors)
    {
        boolean passed = true;

        //scouter info complete
        if (fieldTeamNum.getText().equals("") || fieldMatchNum.getText().equals("") || fieldScouter.getText().equals(""))
        {
            if (reportErrors)
            {
                Utils.showErrorBox("Scouter section not filled out!");
            }
            passed = false;
        }
        //active section unfilled out
        else if (!radioActiveNo.isSelected() && !radioActivePartial.isSelected() && !radioActiveYes.isSelected())
        {
            if (reportErrors)
            {
                Utils.showErrorBox("Robot Activity section not filled out!");
            }
            passed = false;
        }
        //coop unfilled out
        else if (!radioCoopNone.isSelected() && !radioCoopStacked.isSelected() && !radioCoopUnstacked.isSelected())
        {
            if (reportErrors)
            {
                Utils.showErrorBox("Coop section not filled out!");
            }
            passed = false;
        }
        //HP throws but radio unselected
        else if (checkBoxHPThrewNoodles.isSelected() && !radioHPPoor.isSelected() && !radioHPMediocre.isSelected() && !radioHPExcellent.isSelected())
        {
            if (reportErrors)
            {
                Utils.showErrorBox("Human Player section not filled out!");
            }
            passed = false;
        }
        else if (fieldMatchScore.getText().equals(""))
        {
            if (reportErrors)
            {
                Utils.showErrorBox("Final Score not filled out!");
            }
            passed = false;
        }
        return passed;
    }

    /**
     * Gets the AbstractButton's action command for the selected button, or
     * returns the default value if none selected
     *
     * @param buttonGroup
     * @return
     */
    public String getSelectedButtonActionCommandOrDefault(ButtonGroup buttonGroup, String defaultValue)
    {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();)
        {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected())
            {
                return button.getActionCommand().toUpperCase();
            }
        }

        return defaultValue;
    }

    /**
     * Adds a StackContainer to the container stack list
     *
     * @param stack
     */
    public void addItem(StackContainer stack)
    {
        this.addItemToList(listContainerStack, stack);
    }

    /**
     * Adds a StackTote to the tote stack list
     *
     * @param stack
     */
    public void addItem(StackTote stack)
    {
        this.addItemToList(listToteStack, stack);
    }

    /**
     * Adds an object to the given list
     *
     * @param list
     * @param object
     */
    private void addItemToList(javax.swing.JList<StackBase> list, StackBase object)
    {
        ListModel<StackBase> model = list.getModel();
        DefaultListModel<StackBase> newModel = new DefaultListModel<StackBase>();

        //get all elements
        for (int i = 0; i < model.getSize(); i++)
        {
            newModel.add(i, model.getElementAt(i));
        }
        newModel.addElement(object);
        list.setModel(newModel);
        list.updateUI();
    }

    /**
     * Removes all selected elements from the given JList.
     *
     * @param list
     */
    private void removeSelectedFromList(javax.swing.JList<StackBase> list)
    {
        int[] selectedIndicies = list.getSelectedIndices();
        if (selectedIndicies.length > 0)
        {
            ListModel<StackBase> model = list.getModel();
            DefaultListModel<StackBase> newModel = new DefaultListModel<StackBase>();

            //get all elements
            for (int i = 0; i < model.getSize(); i++)
            {
                newModel.add(i, model.getElementAt(i));
            }
            //remove the elements to remove
            newModel.removeRange(selectedIndicies[0], selectedIndicies[selectedIndicies.length - 1]);
            list.setModel(newModel);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MatchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MatchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MatchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MatchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MatchFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddContainerStack;
    private javax.swing.JButton buttonAddToteStack;
    private javax.swing.ButtonGroup buttonGroupCoop;
    private javax.swing.ButtonGroup buttonGroupHumanPlayer;
    private javax.swing.ButtonGroup buttonGroupRobotActive;
    private javax.swing.JButton buttonRemoveContainerStack;
    private javax.swing.JButton buttonRemoveToteStack;
    private javax.swing.JButton buttonSave;
    private javax.swing.JCheckBox checkBoxHPThrewNoodles;
    private javax.swing.JCheckBox checkBoxInAutoZone;
    private javax.swing.JCheckBox checkBoxTotesStacked;
    private javax.swing.JTextField fieldMatchNum;
    private javax.swing.JTextField fieldMatchScore;
    private javax.swing.JTextField fieldScouter;
    private javax.swing.JTextField fieldTeamNum;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelMatchNum;
    private javax.swing.JLabel labelMatchScore;
    private javax.swing.JLabel labelNumContainers;
    private javax.swing.JLabel labelNumTotes;
    private javax.swing.JLabel labelScouter;
    private javax.swing.JLabel labelTeamNum;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JList<StackBase> listContainerStack;
    private javax.swing.JList<StackBase> listToteStack;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane mainPanelScroll;
    private javax.swing.JPanel panelAutoScoredContainer;
    private javax.swing.JPanel panelAutoScoredRobot;
    private javax.swing.JPanel panelAutoScoredTotes;
    private javax.swing.JPanel panelAutonomous;
    private javax.swing.JPanel panelCoop;
    private javax.swing.JPanel panelHumanPlayer;
    private javax.swing.JPanel panelOutcome;
    private javax.swing.JPanel panelRobotActivity;
    private javax.swing.JPanel panelRobotActivityComments;
    private javax.swing.JPanel panelRobotActivityRadio;
    private javax.swing.JPanel panelScoring;
    private javax.swing.JPanel panelTeamInfo;
    private javax.swing.JPanel panelTeleop;
    private javax.swing.JPanel panelTeleopContainerStacks;
    private javax.swing.JPanel panelTeleopToteStacks;
    private javax.swing.JRadioButton radioActiveNo;
    private javax.swing.JRadioButton radioActivePartial;
    private javax.swing.JRadioButton radioActiveYes;
    private javax.swing.JRadioButton radioCoopNone;
    private javax.swing.JRadioButton radioCoopStacked;
    private javax.swing.JRadioButton radioCoopUnstacked;
    private javax.swing.JRadioButton radioHPExcellent;
    private javax.swing.JRadioButton radioHPMediocre;
    private javax.swing.JRadioButton radioHPPoor;
    private javax.swing.JSpinner spinnerNumContainers;
    private javax.swing.JSpinner spinnerNumTotes;
    private javax.swing.JTextArea textAreaRobotActivityComments;
    // End of variables declaration//GEN-END:variables
}
